[package]
name = "gw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
color-eyre = "0.6.2"
duration-string = "0.3.0"
eyre = "0.6.9"
git2 = "0.18.1"
git2_credentials = "0.13.0"
shlex = "1.2.0"
