[package]
name = "gw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
duration-string = "0.3.0"
git2 = "0.18.1"
gumdrop = "0.8.1"
shlex = "1.2.0"
tiny_http = "0.12.0"
