[package]
name = "gw-bin"
description = "Watch git repositories, pull changes and run commands on the new files"
version = "0.1.1"
license = "MIT"
edition = "2021"
documentation = "https://github.com/daniel7grant/gw"
repository = "https://github.com/daniel7grant/gw"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
duration-string = "0.3.0"
git2 = "0.18.1"
gumdrop = "0.8.1"
shlex = "1.2.0"
tiny_http = "0.12.0"

[dev-dependencies]
ureq = { version = "2.9.1", default-features = false }

[profile.release]
strip = true

[[bin]]
name = "gw"
path = "src/main.rs"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }_{ target }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"
