[package]
name = "gw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
dirs = "5.0.1"
duration-string = "0.3.0"
git2 = "0.18.1"
shlex = "1.2.0"
