name: Docker build

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Docker build if we are on a tag
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker meta for Debian
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            danielgrant/gw
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Docker meta for Debian
        id: meta-alpine
        uses: docker/metadata-action@v5
        with:
          images: |
            danielgrant/gw
          tags: |
            type=raw,value=alpine
            type=semver,pattern={{version}},suffix=-alpine
            type=semver,pattern={{major}}.{{minor}},suffix=-alpine
      - name: Build and push Debian Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=danielgrant/gw:latest
          cache-to: type=inline
      - name: Build and push Alpine Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.alpine
          push: true
          tags: ${{ steps.meta-alpine.outputs.tags }}
          labels: ${{ steps.meta-alpine.outputs.labels }}
          cache-from: type=registry,ref=danielgrant/gw:alpine
          cache-to: type=inline
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: danielgrant/gw
