name: Docker build

on:
  push:
    tags:
      - "v*"

env:
  isRcRelease: ${{ contains(github.ref, 'rc') }}
  isLiveRelease: ${{ ! contains(github.ref, 'rc') }}

jobs:
  release:
    name: Docker build if we are on a tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the tag
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker meta for Debian
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            danielgrant/gw
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=danielgrant/gw:latest
          cache-to: type=inline
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        if: ${{ env.isLiveRelease == true }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: danielgrant/gw
