name: Test

on:
  push:

jobs:
  test:
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
    name: Check and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the tag
        uses: actions/checkout@v3
      - name: Add toolchain for Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Test for linting issues
        run: cargo clippy -- -D warnings
      - name: Setup git configuration
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "Test Thomas"
          git config --global init.defaultBranch master
      - name: Run tests
        run: cargo nextest run --no-fail-fast
